# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables: 
  vmImageName: 'ubuntu-latest'


stages:
- stage: Android
  displayName: Android
  
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    
    steps:
      - task: FlutterInstall@0
        inputs:
          channel: 'beta'
          version: 'latest'
      - task: FlutterBuild@0
        inputs:
          target: 'apk'
          projectDirectory: '.'
          buildName: '0.1'
          apkTargetPlatform: 'android-arm64'
      
