trigger:
- main
name: $(BuildID)

stages:
- stage: Windows
  displayName: Windows
  
  jobs:
  - job: ReleaseNotes
    displayName: "Generate release notes"
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: Bash@3
        displayName: "Prepare"
        inputs:
          targetType: 'inline'
          script: |
            mkdir -p  $(build.artifactStagingDirectory)/release-notes/
            touch $(build.artifactStagingDirectory)/release-notes/release-notes.txt

      - task: XplatGenerateReleaseNotes@3
        inputs:
          outputfile: '$(build.artifactStagingDirectory)/release-notes/release-notes.txt'
          templateLocation: 'File'
          templatefile: '.devops/release_notes_template.txt'
          dumpPayloadToConsole: true
          dumpPayloadToFile: false
          replaceFile: false
          getParentsAndChildren: False
          getAllParents: False
          getIndirectPullRequests: False
      
      - task: PublishBuildArtifacts@1
        displayName: "Publish artifacts"
        inputs:
          ArtifactName: 'release-notes'
          
  - job: BuildWindowsDev
    dependsOn: ReleaseNotes
    displayName: "Build Windows DEV"
    pool:
      vmImage: 'windows-latest'
    
    steps:

      - task: FlutterInstall@0
        displayName: "Flutter install"
        inputs:
          channel: 'stable'
          version: 'custom'
          customVersion: '2.0.0'

      - task: Bash@3
        displayName: "Flutter prepare"
        inputs:
          targetType: 'inline'
          script: |
            cd $(Build.SourcesDirectory)
            $(FlutterToolPath)/flutter doctor -v
            $(FlutterToolPath)/flutter precache
            $(FlutterToolPath)/flutter config --enable-windows-desktop
            $(FlutterToolPath)/flutter config --enable-macos-desktop
            $(FlutterToolPath)/flutter config --enable-linux-desktop

      - task: Bash@3
        displayName: "Flutter build icons"
        inputs:
          targetType: 'inline'
          script: |
            cd $(Build.SourcesDirectory)
            $(FlutterToolPath)/flutter pub get
            $(FlutterToolPath)/flutter pub run flutter_launcher_icons:main -f flutter_launcher_icons-dev.yaml 

      - task: FlutterTest@0
        inputs:
          projectDirectory: '$(Build.SourcesDirectory)'
          generateCodeCoverageReport: true

      - task: FlutterBuild@0
        displayName: Windows Debug
        inputs:
          target: 'windows'
          projectDirectory: '$(Build.SourcesDirectory)'
          buildName: '0.1'
          debugMode: true
          buildFlavour: 'dev'
          entryPoint: 'lib/main.dart'
          buildNumber: $(Build.BuildNumber)

          
      - task: CopyFiles@2
        displayName: "Copy artifacts"
        inputs:
          contents: '**/*.exe'
          targetFolder: '$(build.artifactStagingDirectory)/windows/debug'

      - task: Bash@3
        displayName: "Flutter clean"
        inputs:
          targetType: 'inline'
          script: |
            cd $(Build.SourcesDirectory)
            $(FlutterToolPath)/flutter clean
            $(FlutterToolPath)/flutter precache

            
      - task: FlutterBuild@0
        displayName: Windows Release
        inputs:
          target: 'windows'
          projectDirectory: '$(Build.SourcesDirectory)'
          buildName: '0.1'
          buildFlavour: 'dev'
          buildNumber: $(Build.BuildNumber)

      - task: CopyFiles@2
        displayName: "Copy artifacts"
        inputs:
          contents: '**/*.exe'
          targetFolder: '$(build.artifactStagingDirectory)/windows/release'
      - task: PublishBuildArtifacts@1
        displayName: "Publish artifacts"
        inputs:
          ArtifactName: 'dev-windows'

  - job: BuildWindowsStaging
    dependsOn: ReleaseNotes
    displayName: "Build Windows STAGING"
    pool:
      vmImage: 'windows-latest'
    
    steps:
      - task: FlutterInstall@0
        displayName: "Flutter install"
        inputs:
          channel: 'stable'
          version: 'custom'
          customVersion: '2.0.0'

      - task: Bash@3
        displayName: "Flutter clean"
        inputs:
          targetType: 'inline'
          script: |
            cd $(Build.SourcesDirectory)
            $(FlutterToolPath)/flutter clean
            $(FlutterToolPath)/flutter config --enable-windows-desktop
            $(FlutterToolPath)/flutter config --enable-macos-desktop
            $(FlutterToolPath)/flutter config --enable-linux-desktop

      - task: Bash@3
        displayName: "Flutter build icons"
        inputs:
          targetType: 'inline'
          script: |
            cd $(Build.SourcesDirectory)
            $(FlutterToolPath)/flutter pub get
            $(FlutterToolPath)/flutter pub run flutter_launcher_icons:main -f flutter_launcher_icons-staging.yaml 

      - task: FlutterTest@0
        inputs:
          projectDirectory: '$(Build.SourcesDirectory)'
          generateCodeCoverageReport: true

      - task: FlutterBuild@0
        displayName: Windows Release
        inputs:
          target: 'windows'
          projectDirectory: '$(Build.SourcesDirectory)'
          buildName: '0.1'
          buildFlavour: 'staging'
          entryPoint: 'lib/main_staging.dart'
          buildNumber: $(Build.BuildNumber)

      - task: CopyFiles@2
        displayName: "Copy artifacts"
        inputs:
          contents: '**/*.exe'
          targetFolder: '$(build.artifactStagingDirectory)/windows/release'

      - task: PublishBuildArtifacts@1
        displayName: "Publish artifacts"
        inputs:
          ArtifactName: 'staging-windows'
  
  - job: BuildWindowsProd
    dependsOn: ReleaseNotes
    displayName: "Build Widnows PROD"
    pool:
      vmImage: 'windows-latest'
    
    steps:

      - task: FlutterInstall@0
        displayName: "Flutter install"
        inputs:
          channel: 'stable'
          version: 'custom'
          customVersion: '2.0.0'

      - task: Bash@3
        displayName: "Flutter clean"
        inputs:
          targetType: 'inline'
          script: |
            cd $(Build.SourcesDirectory)
            $(FlutterToolPath)/flutter clean
            $(FlutterToolPath)/flutter config --enable-windows-desktop
            $(FlutterToolPath)/flutter config --enable-macos-desktop
            $(FlutterToolPath)/flutter config --enable-linux-desktop

            
      - task: Bash@3
        displayName: "Flutter build icons"
        inputs:
          targetType: 'inline'
          script: |
            cd $(Build.SourcesDirectory)
            $(FlutterToolPath)/flutter pub get
            $(FlutterToolPath)/flutter pub run flutter_launcher_icons:main -f flutter_launcher_icons-prod.yaml 

      - task: FlutterTest@0
        inputs:
          projectDirectory: '$(Build.SourcesDirectory)'
          generateCodeCoverageReport: true
            
      - task: FlutterBuild@0
        displayName: Windows Release
        inputs:
          target: 'windows'
          projectDirectory: '$(Build.SourcesDirectory)'
          buildName: '0.1'
          buildFlavour: 'prod'
          entryPoint: 'lib/main_prod.dart'
          buildNumber: $(Build.BuildNumber)

      - task: CopyFiles@2
        displayName: "Copy artifacts"
        inputs:
          contents: '**/*.exe'
          targetFolder: '$(build.artifactStagingDirectory)/windows/release'

      - task: PublishBuildArtifacts@1
        displayName: "Publish artifacts"
        inputs:
          ArtifactName: 'prod-windows'