name: defichainwallet
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.1
  intl: ^0.17.0-nullsafety.2
  path_provider: ^1.6.27
  url_launcher: ^5.7.10 

  flutter_config: ^1.0.8
  shared_preferences: ^0.5.12+4
  package_info: ^0.4.3+2
  permission_handler: ^5.0.1+1

  #cryto libs
  defichaindart: ^0.1.6
  bip32: ^1.0.7

  #utils
  sprintf: "^4.0.0"

  #ui libs
  carousel_slider: ^2.1.0
  flutter_tagging: ^2.2.0+3
  pull_to_refresh: ^1.6.4 
  auto_size_text: ^2.1.0
  qr_flutter: ^2.0.1
  flutter_qr_reader: ^1.0.3
  flutter_launcher_icons: ^0.8.1

  # Dependency Injection
  get_it: ^5.0.6

  # Securley store data in a keystore
  flutter_secure_storage: ^3.3.5

  # Flare for animations
  flare_flutter: ^2.0.6

  # HTTP client
  http: ^0.12.2

  #database
  sembast: any
  mutex: ^1.1.0

  # Eventbus
  event_taxi: ^0.1.5

  #appcenter
  flutter_appcenter_bundle: ^3.2.0+2
  device_info: 1.0.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo_black.jpg
    - assets/logo_white.jpg
    - assets/logo.png
    - assets/Logo_with_text.png

