name: saiive.live
description: DefiChain and Bitcoin Wallet

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.2.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.1
  intl: ^0.17.0
  path_provider: ^2.0.1
  url_launcher: ^6.0.3

  flutter_dotenv: ^3.1.0
  flutter_config: ^2.0.0
  shared_preferences: ^2.0.5
  package_info_plus  : ^1.0.0
  permission_handler: ^7.1.0

  #cryto libs
  defichaindart: ^2.3.1

  #utils
  sprintf: ^6.0.0 
  logger: ^0.7.0
  logger_flutter: ^0.7.1
  retry: ^3.1.0 
  tuple: ^2.0.0
  mutex: ^3.0.0
  async: ^2.5.0
  
  #ui libs
  carousel_slider: ^3.0.0
  flutter_typeahead: ^3.1.1
  pull_to_refresh: ^2.0.0
  auto_size_text: ^2.1.0
  qr_flutter: ^4.0.0
  flutter_qr_reader: 1.0.3 #do not update
  flutter_launcher_icons: ^0.9.0
  clipboard_manager: ^0.0.4
  flutter_icons: ^1.1.0
  webview_flutter: ^2.0.7

  # Desktop
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

  # Dependency Injection
  get_it: ^7.1.3

  # Securley store data in a keystore
  flutter_secure_storage: ^4.1.0

  # Flare for animations
  flare_flutter: ^3.0.0

  # HTTP client
  http: ^0.13.1

  #database
  sembast: ^3.0.0+4
  sqflite: ^2.0.0+3

  # Eventbus
  event_taxi: ^1.0.0

  #Flutter Vibrate
  flutter_vibrate: ^1.0.0

  #appcenter
  flutter_appcenter_bundle: 3.2.0+2
  device_info: ^2.0.0

  # TouchID/FaceID
  local_auth: ^1.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_intl:
  enabled: true


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo_black.jpg
    - assets/logo_white.jpg
    - assets/logo.png
    - assets/Logo_with_text.png
    - assets/env/.env-Debug
    - assets/env/.env-Prod
    - assets/env/.env-Staging
    - assets/image/


